### ISSUE TITLE
Problem EJB with String attribute

### ISSUE THREAD

**Issue by alberto-yano** [michaelyaakoby/testfun#10]
I put some attributes in EJBs to configure them, so I have:

@Resource( name = "anyURL" )
  private String        anyURL;

This anyURL is configured in JBoss, so JBoss do injection in this attribute for each environment (Desenv, Prod, etc)

testfun failure, because the field anyURL is not an interface... How do I do this?

**Comment by michaelyaakoby** [comment]
Hi Alberto, sorry I missed this - is this still an issue?

**Comment by michaelyaakoby** [comment]
Probably not an issue anymore.
