### ISSUE TITLE
HSQLDB is not supported?

### ISSUE THREAD

**Issue by uaihebert** [michaelyaakoby/testfun#11]
I have the current property in my persistence xml:
     <property name="javax.persistence.jdbc.url" value="jdbc:hsqldb:mem:dbEmMemoria"/>

I am not able to use testfun because it cannot identify a URL with the parameter as: hibernate.connection.url

The JPA spec has the attribute url as valid like below:
javax.persistence.jdbc.url — driver-specific URL

I believe that both should be supported.

**Comment by michaelyaakoby** [comment]
Forgot to close this one... thanks anyways.
