### ISSUE TITLE
Getting 301 redirect when testing with basicAuth("user@host.com", "password")

### ISSUE THREAD

**Issue by gitfan13** [michaelyaakoby/testfun#16]
Michael, many thanks for releasing 0.15 so quickly and for the "Using SecurityContext" example!

Everything works properly except if username is an e-mail address (which in my case it is). In that case the test method returns a 301 Redirect instead of 200 OK.

I guess the reason is that you are adding the username and password to the URL instead of encoding both in base64 and adding them to the headers. That would be too much to expect, so...

Suggestion: just add to the above example a warning that username should not contain any @ characters.

**Comment by michaelyaakoby** [comment]
My bad - I should have used ```URLEncoder.encode()``` when adding the credentials to the URL.
Just pushed a fix - will try and release soon.
