### ISSUE TITLE
I've implemented user roles and authorization

### ISSUE THREAD

**Issue by gitfan13** [michaelyaakoby/testfun#17]
Hi Michael,

unfortunately I have difficulties working with my personal git repo and with the github's repo at the same time, so I cannot create a proper pull request for this.

However I was able to download your code and with just a few changes I've implemented real user authentication an authorization. I've also extended `ExampleResource` and `SecurityContextExampleTest`.

If you are interested in getting and looking at the code, please contact me at boji@swalk-app.com.

Thanks!

**Comment by michaelyaakoby** [comment]
Yeah, sure. Closing this issue and going offline.
