### ISSUE TITLE
Support for ExceptionMapper seems to be missing

### ISSUE THREAD

**Issue by gitfan13** [michaelyaakoby/testfun#19]
Hi,

I've implemented exception handling as suggested in http://howtodoinjava.com/resteasy/exception-handling-in-jax-rs-resteasy-with-exceptionmapper/, which seems quite elegant, but now my tests are failing with `[Expected response with status 400 (Bad Request) but got response with status 500 (Internal Server Error)] expected:<[Bad Request]> but was:<[Internal Server Error]>`.

Previously my REST methods were returning a Response in every case:

```
try {
     Entity entity = createEntityAndPossiblyThrowBlException();
     return Response.status(Status.CREATED).entity(entity).build();
} catch (BlException ble) {
     return new RestErrorDto(ble).response();
}
```

With the new scheme the conversion from BlException into a RestErrorDto happens inside the Exception mapper:

```
@Provider
public class BlExceptionHandler implements ExceptionMapper<BlException>
{
	@Override
	public Response toResponse(final BlException ble)
	{
		return new RestErrorDto(ble).response();
	}
}
```

And my REST methods are much simpler:

```
Entity entity = createEntityAndPossiblyThrowBlException();
return Response.status(Status.CREATED).entity(entity).build();
```

However testfun does not seem to invoke my BlExceptionHandler whenever the method throws an exception and reports the 500 code instead.

**Comment by michaelyaakoby** [comment]
Hi there.
If I remember correctly, you need to make the mapper available to your tests.
Try to add a test resource `src\test\resources\META-INF\services\javax.ws.rs.ext.Providers` containing the full name of your mapper (`com...BlExceptionHandler`).
This should allow the container to find @Provider annotation.

**Comment by michaelyaakoby** [comment]
Keep in mind that testfun doesn't really implement JAX-RS, it merely wraps around it for convenience.
The `javax.ws.rs.ext.Providers` is part of the standard.

**Comment by gitfan13** [comment]
Works perfectly, thanks a lot!
