### ISSUE TITLE
SecurityContext.getUserPrincipal() returns null with resteasy.version = 3.0.20.Final

### ISSUE THREAD

**Issue by gitfan13** [michaelyaakoby/testfun#20]
Hi,

when my code depends on resteasy.version 3.0.8.Final and jee 0.16, my tests run successfully and my code executes correctly in WildFly 9.0.1.

However when I switch my resteasy dependency to 3.0.20.Final the following happens:

- In my unit tests, when I try to access `securityContext.getUserPrincipal().getName()` in any REST method I get a NullPointer Exception. Because `securityContext.getUserPrincipal()` is null.
- However the productive code runs successfully in WildFly.

I was unable to find the place in testfun where the security context is created...

Thanks in advance!

**Comment by gitfan13** [comment]
You have a local dependency on restassured also. What happens if you change it to 3.0.20 and run your tests?

**Comment by adhiraima** [comment]
Has there been any updates on this fix. I am also getting this error and need urgent resolution.

Thanks in advance.

**Comment by michaelyaakoby** [comment]
Hi guys, I haven't been here for a while so I missed this thread.
Will try to update all the libs to latest and see if I can make it work.

**Comment by michaelyaakoby** [comment]
I managed to upgrade all the libs and pushed this to branch features/upgrade_libs .
Most of the test are successful, tough `SecurityContextExampleTest` is still failing.
Once that's done, I'll merge to master and then will release.

**Comment by michaelyaakoby** [comment]
Released version 1.0.
